// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYK90Ag7FOfjlam6-E5kaMQyi9FhEc-q4',
    appId: '1:179414069579:web:6cb2cfd4cb76339d9e38ce',
    messagingSenderId: '179414069579',
    projectId: 'pet-shop-33d45',
    authDomain: 'pet-shop-33d45.firebaseapp.com',
    storageBucket: 'pet-shop-33d45.appspot.com',
    measurementId: 'G-VTTG73BQ8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACw0CggfI3G_pd3heMkkW2E2IPQOezPhs',
    appId: '1:179414069579:android:cc01407d9847c1f89e38ce',
    messagingSenderId: '179414069579',
    projectId: 'pet-shop-33d45',
    storageBucket: 'pet-shop-33d45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBelzyiYFdAULQdAPu92e57wyH53_2Kw5k',
    appId: '1:179414069579:ios:53b42aa24b171abd9e38ce',
    messagingSenderId: '179414069579',
    projectId: 'pet-shop-33d45',
    storageBucket: 'pet-shop-33d45.appspot.com',
    androidClientId: '179414069579-dnilncs6tatfgsuumm9i41frepna6ppt.apps.googleusercontent.com',
    iosClientId: '179414069579-7fh9574n0sbcnnjp9pkvt5m06ra56kuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBelzyiYFdAULQdAPu92e57wyH53_2Kw5k',
    appId: '1:179414069579:ios:53b42aa24b171abd9e38ce',
    messagingSenderId: '179414069579',
    projectId: 'pet-shop-33d45',
    storageBucket: 'pet-shop-33d45.appspot.com',
    androidClientId: '179414069579-dnilncs6tatfgsuumm9i41frepna6ppt.apps.googleusercontent.com',
    iosClientId: '179414069579-7fh9574n0sbcnnjp9pkvt5m06ra56kuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );
}
